src/Auth/bootstrap-stubs/auth/verify.stub
References PR: https://github.com/laravel/framework/pull/29179
The styling of the link will appear exactly the same as it did before:
-----
=> Use POST to send email verification.

src/AuthCommand.php
Each Command instance holds the Laravel application instance as it's property. Just call `$this->laravel->getNamespace()` to access the application namespace instead of using a trait.
=> Call getNamespace from the laravel property

src/Presets/react-stubs/Example.js
Changed the Example.js component in react preset stub to a functional component.
**Why?**
Since React is encouraging functional components over class components, I believe it will be nice to encourage people use it that way in Laravel too.
Create react app also changed it so why don't we follow their steps? ;)
=> Change react preset example stub to functional component

src/Presets/bootstrap-stubs/bootstrap.js
Since the X-CSRF-TOKEN header was [recently removed](https://github.com/laravel/laravel/pull/5083) from Laravel's core `bootstrap.js`, it probably makes sense to remove it from UI as well.
=> Remove X-CSRF-TOKEN header from Axios instance

src/Presets/bootstrap-stubs/bootstrap.js
The default laravel's [bootstrap.js](https://github.com/laravel/laravel/blob/master/resources/js/bootstrap.js#L19) file has a semicolon in the Echo import statement and even though the missing one in the scaffolded file is not strictly required, it causes an unnecessary diff if it is not there when the scaffolding happens.
=> Add missing semicolon to avoid unnecessary diff

src/Presets/Vue.php
As the `laravel/laravel`'s [package.json](https://github.com/laravel/laravel/blob/master/package.json#L17) file, it now uses the caret constraint instead of a fixed dependency version
=> Update resolve-url-loader dependency constraint

src/AuthCommand.php
When scaffolding auth, copy the new password confirm stub. Currently you get an error unless you manually copy the template: https://flareapp.io/share/W7z1K2Pw#F48
References laravel/framework#30214 and laravel/ui#34
=> Add auth.passwords.confirm to exported views

src/Auth/bootstrap-stubs/auth/passwords/confirm.stub
Since the re-authentication timeout is configurable by the user (as described in [laravel/framework#30214](https://github.com/laravel/framework/pull/30214)), I don't think we should hard code "a few hours" in the template.
Therefore, I now opted for "a certain amount of time", however let me know if you come across something more suitable.
=> Change the specified time until re-authentication

src/Presets/bootstrap-stubs/bootstrap.js
Sync default bootstrap.js with the stub provided here.
> The `encrypted` option for Pusher is deprecated and replaced with `forceTLS`.
More info: https://github.com/laravel/laravel/pull/5159
=> update echo parameter

src/Presets/react-stubs/webpack.mix.js, src/Presets/vue-stubs/webpack.mix.js
Use the same indentation as Laravel's default [webpack.mix.js file](https://github.com/laravel/laravel/blob/master/webpack.mix.js#L15).
=> Fix indentation to avoid unnecessary diff

auth-backend/AuthenticatesUsers.php, auth-backend/ConfirmsPasswords.php, auth-backend/RegistersUsers.php, auth-backend/SendsPasswordResetEmails.php, auth-backend/VerifiesEmails.php
In this PR I updated the @returns for multiple functions in de auth-backend folder. This because they don't correctly represent the value that's being returned.
In 4/5 cases there is a view() returned which actually returns \Illuminate\View\View.
=> [2.x] Add \Illuminate\View\View as return value in doc-blocks

src/AuthCommand.php
This will prevent the `HomeController` from being overwritten when scaffolding the auth files.
Closes https://github.com/laravel/ui/issues/94
=> [2.x] Confirm controller overwrite

src/AuthCommand.php
The PR #95 introduced an issue; 
The `HomeController.php` is no longer created when it doesn't exists on a fresh Laravel project.
This fix the issue I initially saw on stackoverflow https://stackoverflow.com/questions/61501766/laravel-7-auth-no-homecontroller
=> Fix confirm controller overwrite

src/AuthRouteMethods.php
I appreciate all the work you and the team are doing. When upgrading from Laravel >= 5.7 and now 6.x to 7.x some of the methods and classes have changed. I kept getting a login and logout conflict with our web routes. I had to dig down and find this reference. The $options attribute is a great way to turn on/off routes but it seems a little incomplete. There are so many more suggestion dealing with following existing controller method naming conventions, should the options be in an auth configuration, etc. but wanted to focus on a low hanging fruit (this use case).
Use case: Web route name "login" and "logout" is defined but still want to use auth routes "registration" and "reset". Was able to turn on/off everything except "login" and "logout" routes.
I could see this being implemented in …
=> Suggestion for update to AuthRouteMethods

auth-backend/ResetsPasswords.php
With a route like the following, `$token` in `showResetForm(Request $request, $token = null)` will give the value of `{subdomain}` and not `{token}` because route parameters are injected based on their order.
```
Route::group(['domain' => '{subdomain}.example.com'], function () {
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
});
```
This pull request proposes that the token is explicitly fetched by name to avoid this.
I have submitted this to the master branch because it could break sites that do not use `Auth::routes()` where `{token}` is the standard parameter name.
=> [3.x] Fetch reset token explicitly.

auth-backend/AuthenticatesUsers.php, auth-backend/ConfirmsPasswords.php, auth-backend/RegistersUsers.php, auth-backend/SendsPasswordResetEmails.php, auth-backend/VerifiesEmails.php
Empty strings aren't valid JSON. These changes make sure that valid JSON is sent back even though the responses are empty.
Fixes https://github.com/laravel/ui/issues/137
=> [2.x] Use proper json responses

src/AuthRouteMethods.php
When removing the Route default namespace (as is default in Laravel 8), the Auth routes will break. This is the case for new Laravel 8 apps, but also when you want to upgrade to match the new defaults.
I understand this package is now deprecated, but if this is the only change it might be worth considering to give users the time to upgrade/change/get comfortable to Jetstream and let it stabilize/grow a bit first.
This checks if the Class with namespace exists. If it doesn't, it adds the default namespace, to compensate for https://github.com/laravel/laravel/commit/58a98efb86c0c0a819e333a52eccf2a7de652f15#diff-b467cc786635bd6945b17726282f1c64
Fixes #138 #141 #142
=> [2.x] Add namespace check to Auth routes

src/Presets/Bootstrap.php, src/Presets/bootstrap-stubs/webpack.mix.js
This fixes an issue with Laravel 8 where the bootstrap preset still needs sass to compile its CSS assets.
Fixes https://github.com/laravel/ui/issues/144
=> [2.x] Fix Bootstrap preset

stubs/Auth/RegisterController.stub
Fix the default path for the User model.
When I run a new project from version 8 I found this problem.
`Class 'App\User' not found`
=> Fix: Class 'App\User' not found

src/Auth/stubs/routes.stub
As Laravel 8.x has done away with the default namespace, the `HomeController` needs to reference the full class path.
Have also swapped to tuple notation, as this is how the docs are demonstrating registration.
=> Update home route registration

README.md
Laravel/UI Readme doesn't contain the documentation on how to use it, it only has link to the documentation which currently says "Page not found", cause there's no "Frontend" page in Laravel 8.x anymore.
I realize that Laravel/UI is not actively maintained, but for those who do want to use it, I think working link to the documentation will be useful.
=> [3.x] Readme: correct link to the documentation

auth-backend/ResetsPasswords.php
The `$token` parameter is removed. #130
=> [3.x] Update PHPDoc comment

src/Auth/bootstrap-stubs/layouts/app.stub
personally i often run this with the `--auth` flag just to get this stub and delete some of the files i don't need for that project.
this small change would prevent the layout file from throwing an exception when you've removed the `Auth::routes` from the web routing file. 
(+ the `register` one below it already has the check too and is enabled by default anyways, just like `login` is)
> feel free to either merge this or close it, i'll be happy either way but i thought i would just leave this here to be nice 😃
=> [3.x] Wrap login link in app.stub with a route check

composer.json
As mentioned in [#178](https://github.com/laravel/ui/pull/178#issuecomment-719910329)
@driesvints I removed the `require-dev` and `autoload-dev` block as there are no tests yet. (The composer.json file is aligned with the 3.x branch now). If I should revert this change, let me know
=> [1.x] Support PHP 8

composer.json
As mentioned in [#178](https://github.com/laravel/ui/pull/178#issuecomment-719910329)
@driesvints I removed the `require-dev` and `autoload-dev` block as there are no tests yet. (The composer.json file is aligned with the 3.x branch now). If I should revert this change, let me know
=> [2.x] Support PHP8

auth-backend/ThrottlesLogins.php
To make it uniform with other files in the directory, we need to use trans instead of Lang::get
=> [3.x] Use trans helper instead of Lang Facade

auth-backend/AuthenticatesUsers.php
The current behaviour is such that when an unauthenticated user is accessing a confirmation-protected route, they are first asked to log in and then instantly asked to confirm the password. That confuses users and also is redundant as they just entered the password.
I have made the most straightforward solution here — explicitly set the `password_confirmed_at` timestamp as the user logs in.
=> Set `password_confirmed_at` on login

src/Auth/bootstrap-stubs/auth/login.stub, src/Auth/bootstrap-stubs/auth/passwords/email.stub, src/Auth/bootstrap-stubs/auth/passwords/reset.stub, src/Auth/bootstrap-stubs/auth/register.stub
In laravel/framework "email" is used instead of "e-mail". To be more consistent, it would be nice to use that same notation here.
=> Use the same notation for email as Laravel Framework does

auth-backend/ThrottlesLogins.php, composer.json, tests/AuthBackend/ThrottleLoginsTest.php
Update on work for this PR: https://github.com/laravel/ui/pull/216
Now that transliteration exists in Core, I've replaced the existing method in UI with its Str helper equivalent.
Not sure if you also want to bump the other core requirements for consistency sake.
=> [3.x] Replace removeSpecialCharacters method with Str Helper Equivalent

auth-backend/AuthenticatesUsers.php, tests/AuthBackend/AuthenticatesUsersTest.php
`$request->boolean()` is available on the minimum version supported by `laravel/ui`: https://github.com/laravel/framework/blob/v8.42.0/src/Illuminate/Http/Concerns/InteractsWithInput.php#L272-L284
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Fixes AuthenticatesUsers always force remember me

src/Presets/React.php, src/Presets/Vue.php, src/Presets/bootstrap-stubs/bootstrap.js, src/Presets/bootstrap-stubs/vite.config.js, src/Presets/react-stubs/vite.config.js, src/Presets/vue-stubs/vite.config.js
This PR updates `master` with the following changes:
* Updates the Vue and React plugin for Vite 3 support.
* Updates an env var to match `laravel/laravel` (https://github.com/laravel/laravel/pull/5929)
* Enables the Blade refreshing feature to match `laravel/laravel`.
* Removes some unnecessary webpack packages.
=> [4.x] Vite 3

.github/workflows/tests.yml, composer.json
=> Drop support for Laravel 8 and PHP 7.3 & 7.4

composer.json, src/AuthCommand.php, src/ControllersCommand.php, src/UiCommand.php
This pull request improves the console output of Laravel UI.
=> [4.x] Improves console output

src/Presets/vue-stubs/app.js
The current suggestion was deprecated with Vite 3.
See: https://vitejs.dev/guide/migration.html#import-meta-glob
=> [4.x] update deprecated globing mechanism

.github/workflows/tests.yml, composer.json, src/Presets/bootstrap-stubs/bootstrap.js
Lodash was removed from the Laravel skeleton in v10.
There is no usage of lodash in the `ui` package.
related issue: https://github.com/laravel/framework/issues/46128
=> Remove lodash import
