src/Auth/bootstrap-stubs/auth/verify.stub
=> replace tab to space

src/Auth/bootstrap-stubs/auth/passwords/confirm.stub
This screen goes along with the new password confirmation functionality. See https://github.com/laravel/framework/pull/30214
=> Add password confirmation screen

README.md
This PR add React as a starting point, like Bootstrap and Vue
=> add React to README.md

src/AuthRouteMethods.php
Update void return to callable
=> [2.x] Fix bad return in comment

src/AuthRouteMethods.php
=> Correct return type

stubs/Auth/RegisterController.stub
=> Revert "Fix: Class 'App\User' not found"

src/AuthRouteMethods.php
This isn't needed anymore since Laravel 8 is now supported on 3.x
Fixes https://github.com/laravel/ui/issues/158
=> [2.x] Revert "[2.x] Add namespace check to Auth routes"

src/Presets/bootstrap-stubs/webpack.mix.js
this stops the browser console from complaining :)
=> [3.x] Add sourcemaps to webpack config

README.md
Shields.io works a lot better than the old pugx.org.
=> [3.x] Update the badges to use shields.io

README.md
There is no longer a note that this package should not be used for new projects. 
However, there is no actual documentation. This PR adds the latest information from branch 7. *
=> [3.x] Added documentation

README.md
=> [3.x] Add support info for older laravel version

README.md
Slightly cleans this section up and adds some additional info.
=> [3.x] Format supported versions

composer.json
=> [3.x] Support PHP 8

src/Auth/bootstrap-stubs/layouts/app.stub
> removes stray spaces accidentally introduced by @driesvints in #177 (phpstorm noticed it in the diff of a new project)
=> [3.x] Removes accidental spaces from app.stub

auth-backend/ResetsPasswords.php, composer.json
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Use new `Password::defaults()` feature.

.github/workflows/tests.yml, composer.json, phpunit.xml.dist, tests/AuthBackend/AuthenticatesUsersTest.php, tests/AuthBackend/RegistersUsersTest.php
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Add basic feature tests

src/Auth/bootstrap-stubs/auth/login.stub, src/Auth/bootstrap-stubs/auth/passwords/confirm.stub, src/Auth/bootstrap-stubs/auth/passwords/email.stub, src/Auth/bootstrap-stubs/auth/passwords/reset.stub, src/Auth/bootstrap-stubs/auth/register.stub
Thanks @madbob for the B5 conversion! 😎 
The `text-md-right` was forgotten, this is now `text-md-end`
https://getbootstrap.com/docs/5.1/utilities/text/
=> Bootstrap 5 text alignment

src/Auth/bootstrap-stubs/layouts/app.stub
Source: https://getbootstrap.com/docs/5.1/components/dropdowns/#responsive-alignment
=> Update app.stub with correct Bootstrap 5 class

src/Presets/Bootstrap.php
=> bump bootstrap version to latest

src/Presets/Vue.php
Updated vue plugin, as the older version is causing npm install dependency issues.
=> Update @vitejs/plugin-vue version

src/Auth/bootstrap-stubs/layouts/app.stub
fonts.bunny.net should be prefetched instead of google fonts one.
=> Update app.stub to preload the right font source

src/Presets/bootstrap-stubs/bootstrap.js
Backport laravel/laravel#6059.
=> [4.x] Support pusher-js v8.0
